'use client';
import {useEffect,useRef,useState} from 'react';
import {api} from '@/services/api';
import {useAccess} from '@/contexts/AccessContext';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {toast} from 'react-toastify';
type Fiscal={documentNo?:string;status:string;requestId?:string;message?:string};
type Notice={id:string;customerName:string;customerTaxId?:string;total:string;status:string;documentNo?:string;requestId?:string;message?:string;createdAt:string;paidAt?:string;receiptFatura?:{id:string;metodoPagamento:string;fiscalSubmission?:Fiscal};session:{mesa:{number:number}};payload:{taxRegistrationNumber:string;lines:{productDescription:string;quantity:number;creditAmount:number;taxes:{taxContribution:number}[]}[]}};
const money=(v:number|string)=>Number(v).toLocaleString('pt-AO',{minimumFractionDigits:2,maximumFractionDigits:2})+' Kz';
const accepted=(s:string)=>['VALID','VALID_PENALTY','PROCESSED_SUCCESS'].includes(s.toUpperCase());
const day=(v:string)=>{const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export default function BillingNotices(){
 const {can}=useAccess();const lock=useRef(false);
 const [rows,setRows]=useState<Notice[]>([]),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [status,setStatus]=useState('all'),[start,setStart]=useState(''),[end,setEnd]=useState('');
 const [selected,setSelected]=useState<Notice|null>(null),[method,setMethod]=useState('dinheiro'),[confirmed,setConfirmed]=useState(false);
 async function load(){setLoading(true);try{setRows((await api.get('/billing-notices')).data);}catch{toast.error('Não foi possível carregar os avisos.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function refresh(n:Notice){if(lock.current)return;lock.current=true;setBusy(true);try{await api.post(`/billing-notices/${n.id}/status`);await load();}catch{toast.error('Não foi possível consultar o estado.');}finally{lock.current=false;setBusy(false);}}
 async function pay(){if(!selected||!confirmed||lock.current)return;lock.current=true;setBusy(true);try{await api.post(`/billing-notices/${selected.id}/pay`,{method,amount:Number(selected.total),confirmed:true});setSelected(null);setConfirmed(false);await load();toast.success('Pagamento registado. Recibo AR enfileirado para emissão.');}catch(e:any){toast.error(e.response?.data?.error||'Não foi possível confirmar. Atualize antes de tentar novamente.');}finally{lock.current=false;setBusy(false);}}
 async function printQr(n:Notice,receipt=false){try{const response=await api.get(`/billing-notices/${n.id}/qrcode${receipt?'?receipt=1':''}`,{responseType:'blob'});const url=URL.createObjectURL(response.data);const w=window.open('','_blank','width=500,height=600');if(!w)throw new Error('popup');w.document.write(`<html><body style="text-align:center;font-family:Arial"><h2>${receipt?'AR':'AC'} — ${n.documentNo||''}</h2><img src="${url}" style="width:360px" onload="window.print()" /></body></html>`);w.document.close();}catch(e:any){toast.error(e.response?.data?.error||'QR Code ainda não está disponível.');}}
 async function pdf(n:Notice,receipt=false){try{
  const {jsPDF}=await import('jspdf');const {default:autoTable}=await import('jspdf-autotable');const doc=new jsPDF();const fiscal=n.receiptFatura?.fiscalSubmission;
  doc.setFontSize(16);doc.text(receipt?'AVISO DE COBRANÇA / RECIBO':'AVISO DE COBRANÇA',14,18);doc.setFontSize(10);
  doc.text([receipt?(fiscal?.documentNo||'Recibo em processamento'):(n.documentNo||'Aviso em processamento'),`Estado fiscal: ${receipt?fiscal?.status:n.status}`,`NIF emissor: ${n.payload.taxRegistrationNumber}`,`Cliente: ${n.customerName}`,`NIF cliente: ${n.customerTaxId||'N/A'}`,`Data: ${new Date(receipt?n.paidAt!:n.createdAt).toLocaleDateString('pt-PT')}`],14,28);
  if(receipt){autoTable(doc,{startY:70,head:[['Documento liquidado','Valor recebido']],body:[[n.documentNo||'',money(n.total)]]});doc.text(`Método: ${n.receiptFatura?.metodoPagamento||''}`,14,110);}
  else autoTable(doc,{startY:70,head:[['Produto','Qtd.','Base','IVA']],body:n.payload.lines.map(l=>[l.productDescription,l.quantity,money(l.creditAmount),money(l.taxes.reduce((s,t)=>s+t.taxContribution,0))]),foot:[['Total','','',money(n.total)]],margin:{bottom:25},didDrawPage:()=>{doc.text(n.paidAt?'Liquidado — consulte o recibo associado.':'Por pagar — não comprova pagamento.',14,285);}});
  doc.save(`${receipt?'AR':'AC'}-${n.id}.pdf`);
 }catch{toast.error('Não foi possível gerar o PDF.');}}
 const visible=rows.filter(n=>(status==='all'||(status==='paid'?!!n.paidAt:!n.paidAt))&&(!start||day(n.createdAt)>=start)&&(!end||day(n.createdAt)<=end)&&`${n.customerName} ${n.customerTaxId||''} ${n.documentNo||''} ${n.receiptFatura?.fiscalSubmission?.documentNo||''} ${n.session.mesa.number}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="space-y-5"><h1 className="text-2xl font-bold">Avisos de cobrança</h1><p>Emita ao concluir a mesa. Consulte os avisos e registe aqui os pagamentos posteriores.</p>
 <div className="flex flex-wrap gap-3"><Input className="sm:max-w-sm" aria-label="Pesquisar cobranças" placeholder="Cliente, NIF, número ou mesa" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Estado do pagamento" className="rounded border bg-background px-3" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos</option><option value="pending">Por pagar</option><option value="paid">Pagos</option></select><label>De<Input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Até<Input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><Button disabled={busy||loading} variant="outline" onClick={load}>Atualizar lista</Button></div>
 {loading?<p>A carregar…</p>:!visible.length?<p>Nenhum aviso encontrado.</p>:visible.map(n=><article key={n.id} className="rounded-xl border p-5 space-y-2"><h2 className="font-semibold">{n.customerName} — {money(n.total)}</h2><p>{n.documentNo||'Número fiscal pendente'} · Mesa {n.session.mesa.number} · {new Date(n.createdAt).toLocaleDateString('pt-PT')}</p><p className={n.paidAt?'text-green-700 font-semibold':'text-amber-700 font-semibold'}>{n.paidAt?'Pago':'Por pagar'}</p><p>Estado fiscal AC: {n.status}</p>{n.message&&<p>{n.message}</p>}{n.receiptFatura&&<p>Recibo AR: {n.receiptFatura.fiscalSubmission?.documentNo||'A emitir'} · {n.receiptFatura.fiscalSubmission?.status}</p>}{n.receiptFatura?.fiscalSubmission?.message&&<p>{n.receiptFatura.fiscalSubmission.message}</p>}
 <div className="flex flex-wrap gap-3"><Button variant="outline" disabled={busy||!n.requestId} onClick={()=>refresh(n)}>Consultar estado fiscal</Button>{can('invoices.print')&&<><Button variant="outline" onClick={()=>pdf(n)}>Imprimir aviso</Button>{accepted(n.status)&&<Button variant="outline" onClick={()=>printQr(n)}>Imprimir QR do AC</Button>}{n.paidAt&&n.receiptFatura?.fiscalSubmission?.documentNo&&<><Button variant="outline" onClick={()=>pdf(n,true)}>Imprimir recibo AR</Button>{accepted(n.receiptFatura.fiscalSubmission.status)&&<Button variant="outline" onClick={()=>printQr(n,true)}>Imprimir QR do AR</Button>}</>}</>}{!n.paidAt&&can('invoices.pay')&&<Button disabled={busy||!n.documentNo||!accepted(n.status)} onClick={()=>{setSelected(n);setConfirmed(false);}}>Registar pagamento e emitir recibo</Button>}</div>{!n.paidAt&&!accepted(n.status)&&<p className="text-sm text-muted-foreground">Consulte o estado e aguarde a aceitação fiscal antes de registar o pagamento.</p>}</article>)}
 {selected&&<div role="dialog" aria-modal="true" aria-label="Registar pagamento" className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-lg space-y-4 rounded-xl bg-background p-6"><h2 className="text-xl font-bold">Receber {money(selected.total)}</h2><p>{selected.customerName} · {selected.documentNo}</p><label className="block">Método<select className="block w-full rounded border bg-background p-3" value={method} disabled={busy} onChange={e=>setMethod(e.target.value)}>{['dinheiro','cartao','multicaixa','transferencia','outro'].map(m=><option key={m} value={m}>{m}</option>)}</select></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>Confirmo que recebi o valor integral.</label><p className="text-sm">Será emitido um AR associado a este aviso, sem repetir a venda.</p><div className="flex gap-2"><Button disabled={busy} variant="outline" onClick={()=>setSelected(null)}>Cancelar</Button><Button aria-busy={busy} disabled={busy||!confirmed} onClick={pay}>{busy?'A registar…':'Confirmar pagamento'}</Button></div></div></div>}
 </section>;
}
